// <auto-generated />
using System;
using DeliBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeliBot.Console.Migrations
{
    [DbContext(typeof(DeliBotContext))]
    [Migration("20210203000225_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("DeliBot.Data.Models.GuessGame.GuessHint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("GuessOptionId")
                        .HasColumnType("int");

                    b.Property<string>("Hint")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("GuessOptionId");

                    b.ToTable("GuessHints");
                });

            modelBuilder.Entity("DeliBot.Data.Models.GuessGame.GuessOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("GuessOptions");
                });

            modelBuilder.Entity("DeliBot.Data.Models.GuessGame.GuessPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CropPicUrl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FullPicUrl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("GuessOptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuessOptionId");

                    b.ToTable("GuessPictures");
                });

            modelBuilder.Entity("DeliBot.Data.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("DeliBot.Data.Models.GuessGame.GuessHint", b =>
                {
                    b.HasOne("DeliBot.Data.Models.GuessGame.GuessOption", "GuessOption")
                        .WithMany("GuessHints")
                        .HasForeignKey("GuessOptionId");

                    b.Navigation("GuessOption");
                });

            modelBuilder.Entity("DeliBot.Data.Models.GuessGame.GuessOption", b =>
                {
                    b.HasOne("DeliBot.Data.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DeliBot.Data.Models.GuessGame.GuessPicture", b =>
                {
                    b.HasOne("DeliBot.Data.Models.GuessGame.GuessOption", "GuessOption")
                        .WithMany("GuessPictures")
                        .HasForeignKey("GuessOptionId");

                    b.Navigation("GuessOption");
                });

            modelBuilder.Entity("DeliBot.Data.Models.GuessGame.GuessOption", b =>
                {
                    b.Navigation("GuessHints");

                    b.Navigation("GuessPictures");
                });
#pragma warning restore 612, 618
        }
    }
}
